version: '{build}'
branches:
  only:
  - master
  - develop
clone_folder: c:\projects\codoc
image:
- Visual Studio 2015
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
install:
    - git submodule update --init --recursive
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- echo %generator%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%

build:
  project: c:\projects\codoc\build\codoc.sln
  verbosity: minimal
  parallel: true

test_script:
    - cmake --build .
    - cmake --build . --target RUN_TESTS

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - source/
    - cmake/
